name: 'Dependency Review'
on:
  pull_request:
    paths:
      - '.github/workflows/dependency-review.yml'
      - 'Gemfile'
      - 'Gemfile.lock'
      - '**.gemspec'

permissions:
  contents: read

jobs:
  dependency-review:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          # https://spdx.org/licenses/
          allow-licenses: MIT, BSD-3-Clause, BSD-2-Clause, 0BSD, Unlicense, ISC, Apache-2.0
