name: Lint
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  rubocop:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rake rubocop

  dprint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dprint/check@v2.2
        with:
          # Keep same version as used in *.nix
          dprint-version: '0.40.0'

  typos:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Keep same version as used in *.nix
      - uses: crate-ci/typos@v1.16.4
        with:
          files: |
            .
            .github
            .vscode
